_id: IbcApplicationsTransferV1EscrowAddress
type: Request
parentId: fld_wrk_006c30a63329481790739506959817d8a618b4be
modified: 1669842795066
created: 1669842795066
url: "{{ base_url }}/ibc/apps/transfer/v1/channels/{{ channel_id }}/ports/{{
  port_id }}/escrow_address"
name: EscrowAddress returns the escrow address for a particular port and channel id.
description: ""
method: GET
body: {}
parameters: []
headers: []
authentication: {}
metaSortKey: -1669842795066
isPrivate: false
settingStoreCookies: true
settingSendCookies: true
settingDisableRenderRequestBody: false
settingEncodeUrl: true
settingRebuildPath: true
settingFollowRedirects: global
