_id: IbcApplicationsTransferV1DenomTrace
type: Request
parentId: fld_wrk_006c30a63329481790739506959817d8a618b4be
modified: 1669842795065
created: 1669842795065
url: "{{ base_url }}/ibc/apps/transfer/v1/denom_traces/{{ hash }}"
name: DenomTrace queries a denomination trace information.
description: ""
method: GET
body: {}
parameters: []
headers: []
authentication: {}
metaSortKey: -1669842795065
isPrivate: false
settingStoreCookies: true
settingSendCookies: true
settingDisableRenderRequestBody: false
settingEncodeUrl: true
settingRebuildPath: true
settingFollowRedirects: global
