_id: IbcApplicationsTransferV1Params
type: Request
parentId: fld_wrk_006c30a63329481790739506959817d8a618b4be
modified: 1669842795064
created: 1669842795064
url: "{{ base_url }}/ibc/apps/transfer/v1/params"
name: Params queries all parameters of the ibc-transfer module.
description: ""
method: GET
body: {}
parameters: []
headers: []
authentication: {}
metaSortKey: -1669842795064
isPrivate: false
settingStoreCookies: true
settingSendCookies: true
settingDisableRenderRequestBody: false
settingEncodeUrl: true
settingRebuildPath: true
settingFollowRedirects: global
