_id: IbcApplicationsInterchainAccountsControllerV1InterchainAccount
type: Request
parentId: fld_wrk_006c30a63329481790739506959817d8a618b4be
modified: 1669842795068
created: 1669842795068
url: "{{ base_url }}/ibc/apps/interchain_accounts/controller/v1/owners/{{ owner
  }}/connections/{{ connection_id }}"
name: InterchainAccount returns the interchain account address for a given owner
  address on a given connection
description: ""
method: GET
body: {}
parameters: []
headers: []
authentication: {}
metaSortKey: -1669842795068
isPrivate: false
settingStoreCookies: true
settingSendCookies: true
settingDisableRenderRequestBody: false
settingEncodeUrl: true
settingRebuildPath: true
settingFollowRedirects: global
