// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sonr/identity/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	DidBaseContext           string `protobuf:"bytes,1,opt,name=did_base_context,json=didBaseContext,proto3" json:"did_base_context,omitempty"`
	DidImplementationContext string `protobuf:"bytes,2,opt,name=did_implementation_context,json=didImplementationContext,proto3" json:"did_implementation_context,omitempty"`
	DidMethodName            string `protobuf:"bytes,3,opt,name=did_method_name,json=didMethodName,proto3" json:"did_method_name,omitempty"`
	IpfsGateway              string `protobuf:"bytes,4,opt,name=ipfs_gateway,json=ipfsGateway,proto3" json:"ipfs_gateway,omitempty"`
	IpfsApi                  string `protobuf:"bytes,5,opt,name=ipfs_api,json=ipfsApi,proto3" json:"ipfs_api,omitempty"`
	RpDisplayName            string `protobuf:"bytes,6,opt,name=rp_display_name,json=rpDisplayName,proto3" json:"rp_display_name,omitempty"`
	RpId                     string `protobuf:"bytes,7,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	RpOrigin                 string `protobuf:"bytes,8,opt,name=rp_origin,json=rpOrigin,proto3" json:"rp_origin,omitempty"`
	RpIcon                   string `protobuf:"bytes,9,opt,name=rp_icon,json=rpIcon,proto3" json:"rp_icon,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_795aedede39c29d8, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDidBaseContext() string {
	if m != nil {
		return m.DidBaseContext
	}
	return ""
}

func (m *Params) GetDidImplementationContext() string {
	if m != nil {
		return m.DidImplementationContext
	}
	return ""
}

func (m *Params) GetDidMethodName() string {
	if m != nil {
		return m.DidMethodName
	}
	return ""
}

func (m *Params) GetIpfsGateway() string {
	if m != nil {
		return m.IpfsGateway
	}
	return ""
}

func (m *Params) GetIpfsApi() string {
	if m != nil {
		return m.IpfsApi
	}
	return ""
}

func (m *Params) GetRpDisplayName() string {
	if m != nil {
		return m.RpDisplayName
	}
	return ""
}

func (m *Params) GetRpId() string {
	if m != nil {
		return m.RpId
	}
	return ""
}

func (m *Params) GetRpOrigin() string {
	if m != nil {
		return m.RpOrigin
	}
	return ""
}

func (m *Params) GetRpIcon() string {
	if m != nil {
		return m.RpIcon
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "sonrio.sonr.identity.Params")
}

func init() { proto.RegisterFile("sonr/identity/params.proto", fileDescriptor_795aedede39c29d8) }

var fileDescriptor_795aedede39c29d8 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x3d, 0x4f, 0xeb, 0x30,
	0x14, 0x86, 0x93, 0xde, 0x36, 0x6d, 0x7d, 0xef, 0x05, 0x14, 0x2a, 0x61, 0x8a, 0x14, 0x3e, 0x06,
	0xd4, 0x85, 0x64, 0x60, 0x43, 0x2c, 0x14, 0x24, 0xd4, 0x81, 0x0f, 0x31, 0xb2, 0x44, 0x6e, 0x6c,
	0xd2, 0x23, 0x35, 0xb6, 0xe5, 0x18, 0xd1, 0xfc, 0x0b, 0x46, 0x46, 0x7e, 0x0e, 0x1b, 0x1d, 0x19,
	0x51, 0xfb, 0x47, 0x90, 0x4f, 0x54, 0x10, 0x93, 0x7d, 0xde, 0xf7, 0x79, 0x74, 0x86, 0x43, 0xfa,
	0xa5, 0x92, 0x26, 0x01, 0x2e, 0xa4, 0x05, 0x5b, 0x25, 0x9a, 0x19, 0x56, 0x94, 0xb1, 0x36, 0xca,
	0xaa, 0xb0, 0xe7, 0x3a, 0x50, 0xb1, 0x7b, 0xe2, 0x15, 0xd2, 0xef, 0xe5, 0x2a, 0x57, 0x08, 0x24,
	0xee, 0x57, 0xb3, 0x07, 0xef, 0x0d, 0x12, 0xdc, 0xa2, 0x1c, 0x0e, 0xc8, 0x06, 0x07, 0x9e, 0x8e,
	0x59, 0x29, 0xd2, 0x4c, 0x49, 0x2b, 0x66, 0x96, 0xfa, 0x7b, 0xfe, 0xa0, 0x7b, 0xb7, 0xc6, 0x81,
	0x0f, 0x59, 0x29, 0xce, 0xeb, 0x34, 0x3c, 0x25, 0x7d, 0x47, 0x42, 0xa1, 0xa7, 0xa2, 0x10, 0xd2,
	0x32, 0x0b, 0x4a, 0x7e, 0x3b, 0x0d, 0x74, 0x28, 0x07, 0x3e, 0xfa, 0x05, 0xac, 0xec, 0x43, 0xb2,
	0xee, 0xec, 0x42, 0xd8, 0x89, 0xe2, 0xa9, 0x64, 0x85, 0xa0, 0x7f, 0x50, 0xf9, 0xcf, 0x81, 0x5f,
	0x61, 0x7a, 0xcd, 0x0a, 0x11, 0xee, 0x93, 0x7f, 0xa0, 0x1f, 0xca, 0x34, 0x67, 0x56, 0x3c, 0xb1,
	0x8a, 0x36, 0x11, 0xfa, 0xeb, 0xb2, 0xcb, 0x3a, 0x0a, 0xb7, 0x49, 0x07, 0x11, 0xa6, 0x81, 0xb6,
	0xb0, 0x6e, 0xbb, 0xf9, 0x4c, 0x83, 0xdb, 0x62, 0x74, 0xca, 0xa1, 0xd4, 0x53, 0x56, 0xd5, 0x5b,
	0x82, 0x7a, 0x8b, 0xd1, 0x17, 0x75, 0x8a, 0x5b, 0x36, 0x49, 0xcb, 0xe8, 0x14, 0x38, 0x6d, 0x63,
	0xdb, 0x34, 0x7a, 0xc4, 0xc3, 0x1d, 0xd2, 0x35, 0x3a, 0x55, 0x06, 0x72, 0x90, 0xb4, 0x83, 0x45,
	0xc7, 0xe8, 0x1b, 0x9c, 0xc3, 0x2d, 0xd2, 0x76, 0x46, 0xa6, 0x24, 0xed, 0x62, 0x15, 0x18, 0x3d,
	0xca, 0x94, 0x3c, 0x69, 0xbe, 0xbc, 0xee, 0x7a, 0xc3, 0xe1, 0xdb, 0x22, 0xf2, 0xe7, 0x8b, 0xc8,
	0xff, 0x5c, 0x44, 0xfe, 0xf3, 0x32, 0xf2, 0xe6, 0xcb, 0xc8, 0xfb, 0x58, 0x46, 0xde, 0xfd, 0x20,
	0x07, 0x3b, 0x79, 0x1c, 0xc7, 0x99, 0x2a, 0x12, 0x77, 0x9b, 0x23, 0x50, 0xf8, 0x26, 0xb3, 0x9f,
	0x43, 0xda, 0x4a, 0x8b, 0x72, 0x1c, 0xe0, 0x71, 0x8e, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x82,
	0xda, 0x9d, 0x2a, 0xe6, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RpIcon) > 0 {
		i -= len(m.RpIcon)
		copy(dAtA[i:], m.RpIcon)
		i = encodeVarintParams(dAtA, i, uint64(len(m.RpIcon)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.RpOrigin) > 0 {
		i -= len(m.RpOrigin)
		copy(dAtA[i:], m.RpOrigin)
		i = encodeVarintParams(dAtA, i, uint64(len(m.RpOrigin)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.RpId) > 0 {
		i -= len(m.RpId)
		copy(dAtA[i:], m.RpId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.RpId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.RpDisplayName) > 0 {
		i -= len(m.RpDisplayName)
		copy(dAtA[i:], m.RpDisplayName)
		i = encodeVarintParams(dAtA, i, uint64(len(m.RpDisplayName)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.IpfsApi) > 0 {
		i -= len(m.IpfsApi)
		copy(dAtA[i:], m.IpfsApi)
		i = encodeVarintParams(dAtA, i, uint64(len(m.IpfsApi)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.IpfsGateway) > 0 {
		i -= len(m.IpfsGateway)
		copy(dAtA[i:], m.IpfsGateway)
		i = encodeVarintParams(dAtA, i, uint64(len(m.IpfsGateway)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DidMethodName) > 0 {
		i -= len(m.DidMethodName)
		copy(dAtA[i:], m.DidMethodName)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DidMethodName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DidImplementationContext) > 0 {
		i -= len(m.DidImplementationContext)
		copy(dAtA[i:], m.DidImplementationContext)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DidImplementationContext)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DidBaseContext) > 0 {
		i -= len(m.DidBaseContext)
		copy(dAtA[i:], m.DidBaseContext)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DidBaseContext)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DidBaseContext)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DidImplementationContext)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DidMethodName)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.IpfsGateway)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.IpfsApi)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.RpDisplayName)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.RpId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.RpOrigin)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.RpIcon)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidBaseContext", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidBaseContext = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidImplementationContext", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidImplementationContext = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidMethodName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidMethodName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpfsGateway", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IpfsGateway = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpfsApi", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IpfsApi = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RpDisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RpDisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RpId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RpId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RpOrigin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RpOrigin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RpIcon", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RpIcon = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
