// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sonr/identity/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	DidBaseContext   string   `protobuf:"bytes,1,opt,name=did_base_context,json=didBaseContext,proto3" json:"did_base_context,omitempty"`
	DidMethodContext string   `protobuf:"bytes,2,opt,name=did_method_context,json=didMethodContext,proto3" json:"did_method_context,omitempty"`
	DidMethodName    string   `protobuf:"bytes,3,opt,name=did_method_name,json=didMethodName,proto3" json:"did_method_name,omitempty"`
	DidMethodVersion string   `protobuf:"bytes,4,opt,name=did_method_version,json=didMethodVersion,proto3" json:"did_method_version,omitempty"`
	DidNetwork       string   `protobuf:"bytes,5,opt,name=did_network,json=didNetwork,proto3" json:"did_network,omitempty"`
	IpfsGateway      string   `protobuf:"bytes,6,opt,name=ipfs_gateway,json=ipfsGateway,proto3" json:"ipfs_gateway,omitempty"`
	IpfsApi          string   `protobuf:"bytes,7,opt,name=ipfs_api,json=ipfsApi,proto3" json:"ipfs_api,omitempty"`
	HnsTlds          []string `protobuf:"bytes,8,rep,name=hns_tlds,json=hnsTlds,proto3" json:"hns_tlds,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_795aedede39c29d8, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDidBaseContext() string {
	if m != nil {
		return m.DidBaseContext
	}
	return ""
}

func (m *Params) GetDidMethodContext() string {
	if m != nil {
		return m.DidMethodContext
	}
	return ""
}

func (m *Params) GetDidMethodName() string {
	if m != nil {
		return m.DidMethodName
	}
	return ""
}

func (m *Params) GetDidMethodVersion() string {
	if m != nil {
		return m.DidMethodVersion
	}
	return ""
}

func (m *Params) GetDidNetwork() string {
	if m != nil {
		return m.DidNetwork
	}
	return ""
}

func (m *Params) GetIpfsGateway() string {
	if m != nil {
		return m.IpfsGateway
	}
	return ""
}

func (m *Params) GetIpfsApi() string {
	if m != nil {
		return m.IpfsApi
	}
	return ""
}

func (m *Params) GetHnsTlds() []string {
	if m != nil {
		return m.HnsTlds
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "sonrio.sonr.identity.Params")
}

func init() { proto.RegisterFile("sonr/identity/params.proto", fileDescriptor_795aedede39c29d8) }

var fileDescriptor_795aedede39c29d8 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd1, 0x3f, 0x4e, 0xc3, 0x30,
	0x14, 0x06, 0xf0, 0xa4, 0x2d, 0x6d, 0x71, 0xf9, 0x27, 0xab, 0x83, 0xe9, 0x90, 0x16, 0x06, 0xd4,
	0x01, 0x92, 0x81, 0x8d, 0x8d, 0x32, 0x30, 0x51, 0x21, 0x84, 0x18, 0x58, 0x22, 0xb7, 0x36, 0x89,
	0x45, 0xe3, 0x67, 0xc5, 0x86, 0xb6, 0xb7, 0x60, 0x64, 0xe4, 0x14, 0x9c, 0x81, 0xb1, 0x23, 0x23,
	0x6a, 0x2e, 0x82, 0xec, 0xa8, 0x05, 0x75, 0x7a, 0xc9, 0xf7, 0xfd, 0xfc, 0x96, 0x87, 0x3a, 0x1a,
	0x64, 0x1e, 0x09, 0xc6, 0xa5, 0x11, 0x66, 0x1e, 0x29, 0x9a, 0xd3, 0x4c, 0x87, 0x2a, 0x07, 0x03,
	0xb8, 0x6d, 0x3b, 0x01, 0xa1, 0x1d, 0xe1, 0x8a, 0x74, 0xda, 0x09, 0x24, 0xe0, 0x40, 0x64, 0xbf,
	0x4a, 0x7b, 0xfc, 0x59, 0x41, 0xf5, 0x5b, 0xf7, 0x18, 0xf7, 0xd1, 0x01, 0x13, 0x2c, 0x1e, 0x51,
	0xcd, 0xe3, 0x31, 0x48, 0xc3, 0x67, 0x86, 0xf8, 0x3d, 0xbf, 0xbf, 0x7d, 0xb7, 0xc7, 0x04, 0x1b,
	0x50, 0xcd, 0xaf, 0xca, 0x14, 0x9f, 0x22, 0x6c, 0x65, 0xc6, 0x4d, 0x0a, 0x6c, 0x6d, 0x2b, 0xce,
	0xda, 0x1d, 0x37, 0xae, 0x58, 0xe9, 0x13, 0xb4, 0xff, 0x4f, 0x4b, 0x9a, 0x71, 0x52, 0x75, 0x74,
	0x77, 0x4d, 0x87, 0x34, 0xe3, 0x1b, 0x5b, 0x5f, 0x79, 0xae, 0x05, 0x48, 0x52, 0xdb, 0xd8, 0xfa,
	0x50, 0xe6, 0xb8, 0x8b, 0x5a, 0x56, 0x4b, 0x6e, 0xa6, 0x90, 0x3f, 0x93, 0x2d, 0xc7, 0x10, 0x13,
	0x6c, 0x58, 0x26, 0xf8, 0x08, 0xed, 0x08, 0xf5, 0xa4, 0xe3, 0x84, 0x1a, 0x3e, 0xa5, 0x73, 0x52,
	0x77, 0xa2, 0x65, 0xb3, 0xeb, 0x32, 0xc2, 0x87, 0xa8, 0xe9, 0x08, 0x55, 0x82, 0x34, 0x5c, 0xdd,
	0xb0, 0xff, 0x97, 0x4a, 0xd8, 0x2a, 0x95, 0x3a, 0x36, 0x13, 0xa6, 0x49, 0xb3, 0x57, 0xb5, 0x55,
	0x2a, 0xf5, 0xfd, 0x84, 0xe9, 0x8b, 0xda, 0xfb, 0x47, 0xd7, 0x1b, 0x0c, 0xbe, 0x96, 0x81, 0xbf,
	0x58, 0x06, 0xfe, 0xcf, 0x32, 0xf0, 0xdf, 0x8a, 0xc0, 0x5b, 0x14, 0x81, 0xf7, 0x5d, 0x04, 0xde,
	0x63, 0x3f, 0x11, 0x26, 0x7d, 0x19, 0x85, 0x63, 0xc8, 0x22, 0x7b, 0x82, 0x33, 0x01, 0x6e, 0x46,
	0xb3, 0xbf, 0x7b, 0x99, 0xb9, 0xe2, 0x7a, 0x54, 0x77, 0x37, 0x38, 0xff, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0x14, 0xc0, 0xc3, 0x34, 0xcd, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HnsTlds) > 0 {
		for iNdEx := len(m.HnsTlds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.HnsTlds[iNdEx])
			copy(dAtA[i:], m.HnsTlds[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.HnsTlds[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.IpfsApi) > 0 {
		i -= len(m.IpfsApi)
		copy(dAtA[i:], m.IpfsApi)
		i = encodeVarintParams(dAtA, i, uint64(len(m.IpfsApi)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.IpfsGateway) > 0 {
		i -= len(m.IpfsGateway)
		copy(dAtA[i:], m.IpfsGateway)
		i = encodeVarintParams(dAtA, i, uint64(len(m.IpfsGateway)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DidNetwork) > 0 {
		i -= len(m.DidNetwork)
		copy(dAtA[i:], m.DidNetwork)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DidNetwork)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.DidMethodVersion) > 0 {
		i -= len(m.DidMethodVersion)
		copy(dAtA[i:], m.DidMethodVersion)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DidMethodVersion)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DidMethodName) > 0 {
		i -= len(m.DidMethodName)
		copy(dAtA[i:], m.DidMethodName)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DidMethodName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DidMethodContext) > 0 {
		i -= len(m.DidMethodContext)
		copy(dAtA[i:], m.DidMethodContext)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DidMethodContext)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DidBaseContext) > 0 {
		i -= len(m.DidBaseContext)
		copy(dAtA[i:], m.DidBaseContext)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DidBaseContext)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DidBaseContext)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DidMethodContext)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DidMethodName)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DidMethodVersion)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DidNetwork)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.IpfsGateway)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.IpfsApi)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.HnsTlds) > 0 {
		for _, s := range m.HnsTlds {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidBaseContext", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidBaseContext = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidMethodContext", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidMethodContext = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidMethodName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidMethodName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidMethodVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidMethodVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidNetwork", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidNetwork = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpfsGateway", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IpfsGateway = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpfsApi", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IpfsApi = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HnsTlds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HnsTlds = append(m.HnsTlds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
