// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sonr/identity/ssi.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// KeyType is the type of key used to sign a DID document.
type KeyType int32

const (
	// No key type specified
	KeyType_KeyType_UNSPECIFIED KeyType = 0
	// JsonWebKey2020 is a VerificationMethod type. https://w3c-ccg.github.io/lds-jws2020/
	KeyType_KeyType_JSON_WEB_KEY_2020 KeyType = 1
	// ED25519VerificationKey2018 is the Ed25519VerificationKey2018 verification key type as specified here: https://w3c-ccg.github.io/lds-ed25519-2018/
	KeyType_KeyType_ED25519_VERIFICATION_KEY_2018 KeyType = 2
	// ECDSASECP256K1VerificationKey2019 is the EcdsaSecp256k1VerificationKey2019 verification key type as specified here: https://w3c-ccg.github.io/lds-ecdsa-secp256k1-2019/
	KeyType_KeyType_ECDSA_SECP256K1_VERIFICATION_KEY_2019 KeyType = 3
	// RSAVerificationKey2018 is the RsaVerificationKey2018 verification key type as specified here: https://w3c-ccg.github.io/lds-rsa2018/
	KeyType_KeyType_RSA_VERIFICATION_KEY_2018 KeyType = 4
	// WebAuthnAuthentication2018 is the WebAuthnAuthentication2018 verification key type as specified here: https://w3c-ccg.github.io/lds-webauthn/
	KeyType_KeyType_WEB_AUTHN_AUTHENTICATION_2018 KeyType = 5
)

var KeyType_name = map[int32]string{
	0: "KeyType_UNSPECIFIED",
	1: "KeyType_JSON_WEB_KEY_2020",
	2: "KeyType_ED25519_VERIFICATION_KEY_2018",
	3: "KeyType_ECDSA_SECP256K1_VERIFICATION_KEY_2019",
	4: "KeyType_RSA_VERIFICATION_KEY_2018",
	5: "KeyType_WEB_AUTHN_AUTHENTICATION_2018",
}

var KeyType_value = map[string]int32{
	"KeyType_UNSPECIFIED":                           0,
	"KeyType_JSON_WEB_KEY_2020":                     1,
	"KeyType_ED25519_VERIFICATION_KEY_2018":         2,
	"KeyType_ECDSA_SECP256K1_VERIFICATION_KEY_2019": 3,
	"KeyType_RSA_VERIFICATION_KEY_2018":             4,
	"KeyType_WEB_AUTHN_AUTHENTICATION_2018":         5,
}

func (x KeyType) String() string {
	return proto.EnumName(KeyType_name, int32(x))
}

func (KeyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7951e27a89149433, []int{0}
}

// ProofType is the type of proof used to present claims over a DID document.
type ProofType int32

const (
	// No proof type specified
	ProofType_ProofType_UNSPECIFIED ProofType = 0
	// JsonWebSignature2020 is a proof type. https://w3c-ccg.github.io/lds-jws2020/
	ProofType_ProofType_JSON_WEB_SIGNATURE_2020 ProofType = 1
	// ED25519Signature2018 is the Ed25519Signature2018 proof type as specified here: https://w3c-ccg.github.io/lds-ed25519-2018/
	ProofType_ProofType_ED25519_SIGNATURE_2018 ProofType = 2
	// EcdsaSecp256k1Signature2019 is the EcdsaSecp256k1Signature2019 proof type as specified here: https://w3c-ccg.github.io/lds-ecdsa-secp256k1-2019/
	ProofType_ProofType_ECDSA_SECP256K1_SIGNATURE_2019 ProofType = 3
	// RsaSignature2018 is the RsaSignature2018 proof type as specified here: https://w3c-ccg.github.io/lds-rsa2018/
	ProofType_ProofType_RSA_SIGNATURE_2018 ProofType = 4
)

var ProofType_name = map[int32]string{
	0: "ProofType_UNSPECIFIED",
	1: "ProofType_JSON_WEB_SIGNATURE_2020",
	2: "ProofType_ED25519_SIGNATURE_2018",
	3: "ProofType_ECDSA_SECP256K1_SIGNATURE_2019",
	4: "ProofType_RSA_SIGNATURE_2018",
}

var ProofType_value = map[string]int32{
	"ProofType_UNSPECIFIED":                    0,
	"ProofType_JSON_WEB_SIGNATURE_2020":        1,
	"ProofType_ED25519_SIGNATURE_2018":         2,
	"ProofType_ECDSA_SECP256K1_SIGNATURE_2019": 3,
	"ProofType_RSA_SIGNATURE_2018":             4,
}

func (x ProofType) String() string {
	return proto.EnumName(ProofType_name, int32(x))
}

func (ProofType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7951e27a89149433, []int{1}
}

// ServiceType is the type of service used to provide a DID document.
type ServiceType int32

const (
	// No service type specified
	ServiceType_ServiceType_UNSPECIFIED ServiceType = 0
	// DIDCommMessaging is the DIDCommMessaging service type as specified here: https://identity.foundation/didcomm-messaging/spec/
	ServiceType_ServiceType_DID_COMM_MESSAGING ServiceType = 1
	// EncryptedDataVault is the EncryptedDataVault service type as specified here: https://identity.foundation/edv-spec/
	ServiceType_ServiceType_ENCRYPTED_DATA_VAULT ServiceType = 2
)

var ServiceType_name = map[int32]string{
	0: "ServiceType_UNSPECIFIED",
	1: "ServiceType_DID_COMM_MESSAGING",
	2: "ServiceType_ENCRYPTED_DATA_VAULT",
}

var ServiceType_value = map[string]int32{
	"ServiceType_UNSPECIFIED":          0,
	"ServiceType_DID_COMM_MESSAGING":   1,
	"ServiceType_ENCRYPTED_DATA_VAULT": 2,
}

func (x ServiceType) String() string {
	return proto.EnumName(ServiceType_name, int32(x))
}

func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7951e27a89149433, []int{2}
}

func init() {
	proto.RegisterEnum("sonrio.sonr.identity.KeyType", KeyType_name, KeyType_value)
	proto.RegisterEnum("sonrio.sonr.identity.ProofType", ProofType_name, ProofType_value)
	proto.RegisterEnum("sonrio.sonr.identity.ServiceType", ServiceType_name, ServiceType_value)
}

func init() { proto.RegisterFile("sonr/identity/ssi.proto", fileDescriptor_7951e27a89149433) }

var fileDescriptor_7951e27a89149433 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x8f, 0x93, 0x40,
	0x14, 0xc7, 0x61, 0x5d, 0x35, 0x3e, 0x2f, 0x04, 0x35, 0xcd, 0x46, 0x25, 0xbb, 0xc6, 0x26, 0x6b,
	0xe3, 0xc2, 0x82, 0xa9, 0x71, 0x8f, 0x53, 0x98, 0xad, 0x63, 0xed, 0x94, 0x30, 0x43, 0x4d, 0xbd,
	0x4c, 0xd2, 0x8a, 0xca, 0xc1, 0x4e, 0x03, 0x68, 0xe4, 0x5b, 0xf8, 0x9d, 0xbc, 0x78, 0xec, 0xd1,
	0xa3, 0x69, 0x3f, 0x81, 0xdf, 0xc0, 0x80, 0xa5, 0x20, 0x71, 0x2f, 0x0c, 0x93, 0xff, 0xef, 0xbd,
	0xbc, 0xdf, 0xe4, 0x41, 0x27, 0x95, 0xcb, 0xc4, 0x8a, 0xdf, 0x45, 0xcb, 0x2c, 0xce, 0x72, 0x2b,
	0x4d, 0x63, 0x73, 0x95, 0xc8, 0x4c, 0xea, 0x77, 0x8b, 0x20, 0x96, 0x66, 0x71, 0x98, 0x55, 0xde,
	0xfb, 0xad, 0xc2, 0xcd, 0x51, 0x94, 0xf3, 0x7c, 0x15, 0xe9, 0x1d, 0xb8, 0xb3, 0xfb, 0x15, 0x21,
	0x65, 0x3e, 0x76, 0xc9, 0x25, 0xc1, 0x9e, 0xa6, 0xe8, 0x0f, 0xe1, 0xa8, 0x0a, 0x5e, 0xb1, 0x09,
	0x15, 0x6f, 0xf0, 0x40, 0x8c, 0xf0, 0x4c, 0x38, 0xe7, 0xce, 0xb9, 0xa6, 0xea, 0x4f, 0xa0, 0x5b,
	0xc5, 0xd8, 0x73, 0xfa, 0x7d, 0xfb, 0x42, 0x4c, 0x71, 0x40, 0x2e, 0x89, 0x8b, 0x38, 0x99, 0xd0,
	0x1d, 0x6a, 0xbf, 0xd0, 0x0e, 0x74, 0x1b, 0xce, 0xf6, 0xa8, 0xeb, 0x31, 0x24, 0x18, 0x76, 0x7d,
	0xa7, 0xff, 0x7c, 0x64, 0xff, 0xb7, 0xe4, 0x42, 0xbb, 0xa6, 0x77, 0xe1, 0xa4, 0x2a, 0x09, 0x18,
	0xba, 0xa2, 0xf3, 0x61, 0x73, 0x88, 0x62, 0x3c, 0x14, 0xf2, 0x97, 0xb4, 0xfc, 0x62, 0xca, 0x2b,
	0xbc, 0x44, 0xaf, 0xf7, 0xbe, 0xab, 0x70, 0xcb, 0x4f, 0xa4, 0x7c, 0x5f, 0x5a, 0x1f, 0xc1, 0xbd,
	0xfd, 0xa5, 0xe5, 0xdd, 0x85, 0x93, 0x3a, 0xda, 0x9b, 0x33, 0x32, 0xa4, 0x88, 0x87, 0x01, 0xae,
	0xfc, 0x1f, 0xc3, 0x71, 0x8d, 0x55, 0x2f, 0xd0, 0xa4, 0x4a, 0xf5, 0xa7, 0x70, 0xda, 0xa0, 0x5a,
	0xf2, 0xff, 0xd0, 0x85, 0xf5, 0x31, 0x3c, 0xa8, 0xe9, 0xc2, 0xbb, 0xd5, 0xef, 0xb0, 0x97, 0xc1,
	0x6d, 0x16, 0x25, 0x5f, 0xe2, 0x45, 0x54, 0x6a, 0xdc, 0x87, 0x4e, 0xe3, 0xda, 0x12, 0x79, 0x04,
	0x46, 0x33, 0xf4, 0x88, 0x27, 0xdc, 0xc9, 0x78, 0x2c, 0xc6, 0x98, 0x31, 0x34, 0x24, 0x74, 0xf8,
	0xd7, 0xa2, 0xc9, 0x60, 0xea, 0x06, 0x33, 0x9f, 0x63, 0x4f, 0x78, 0x88, 0x23, 0x31, 0x45, 0xe1,
	0x6b, 0xae, 0x1d, 0x0c, 0x06, 0x3f, 0x36, 0x86, 0xba, 0xde, 0x18, 0xea, 0xaf, 0x8d, 0xa1, 0x7e,
	0xdb, 0x1a, 0xca, 0x7a, 0x6b, 0x28, 0x3f, 0xb7, 0x86, 0xf2, 0xf6, 0xf4, 0x43, 0x9c, 0x7d, 0xfc,
	0x3c, 0x37, 0x17, 0xf2, 0x93, 0x55, 0xec, 0xd8, 0x59, 0x2c, 0xcb, 0xd3, 0xfa, 0x5a, 0x6f, 0x63,
	0x96, 0xaf, 0xa2, 0x74, 0x7e, 0xa3, 0x5c, 0xc8, 0x67, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc7,
	0x1d, 0x13, 0xf1, 0xab, 0x02, 0x00, 0x00,
}
